DooringKR/frontend

- src/components/Button/Button.tsx
- src/components/Button/buttonStyles.ts
> 버튼 컴포넌트 작업
> 디자인과 로직은 분리 
> 버튼은 기본적으로 large 사이즈 이지만 추후 확장성을 고려하여 2개의 사이즈로 제작 -> small 사이즈는 추가 변경 가능
> feat: Button 컴포넌트 작성

- src/app/(home)/page.tsx
- src/app/layout.tsx
- src/app/login/page.tsx
- src/utils/formatPhoneNumber.ts
- src/utils/handlePhoneKeyDown.ts
> 로그인 페이지 작업
> 유저 로그인정보(쿠키)가 없을 경우 로그인 페이지로 리디렉션
> 쿠키가 존재할 경우 메인 페이지
> 자동으로 "-"(하이픈) 을 넣어주는 유틸 함수 추가
> 숫자 하이픈 이외에 다른 문자입력을 막는 유틸 함수 추가
> 임시로 쿠키를 넣어 쿠키가 존재 할 경우를 리디렉션
> Feat: Login page 1차 시안 작성 및 임시 쿠키 추가

- src/app/login/page.tsx
> watch 때문에 무한호출 하는 에러를 수정했습니다. 
> Fix: 무한 재귀 호출 에러 수정

- src/components/SearchAddress/DaumPostcode.tsx
- src/components/SearchAddress/SearchAdress.tsx
> 다음 주소 검색 컴포넌트를 구현했습니다. 추후 연결 및 간단한 수정만 하면 되도록 완성 시켰습니다.
> Feat: 다음주소 검색 창 추가

- src/app/api/naver/coordinates/route.ts
- src/app/api/naver/directions/route.ts
- src/components/SearchAddress/DaumPostcode.tsx
- src/components/SearchAddress/SearchAdress.tsx
- src/utils/CheckDeliveryTime.ts
> Feat: 배송 예정시간 유틸 추가

- src/app/login/page.tsx
- src/components/Button/buttonStyles.ts
> Fix: Button

- src/components/Modal/Modal.tsx
> Feat:  Modal 추가

- src/components/Modal/Modal.tsx
> Revert "Feat:  Modal 추가"

- src/app/order/door/select/_components/Flap.tsx
- src/app/order/door/select/_components/Normal.tsx
- src/app/order/door/select/page.tsx
> chore: merge main

- src/app/login/page.tsx
- src/app/order/door/select/page.tsx
> Feat: 로그인 및 경첩 에러 수정

- src/api/authApi.ts
- src/api/checkcash.ts
- src/api/orderApi.ts
- src/app/api/auth/signin/route.ts
- src/app/api/auth/signup/route.ts
- src/app/api/auth/user/route.ts
- src/app/api/checkcash/accessory/route.ts
- src/app/api/checkcash/cabinet/route.ts
- src/app/api/checkcash/door/route.ts
- src/app/api/checkcash/finish/route.ts
- src/app/api/checkcash/hardware/route.ts
- src/app/api/order/route.ts
- src/store/userStore.ts
- src/types/apiType.d.ts
- src/types/authApi.d.ts
> Feat: api 함수 추가

- public/icons/Arrow_Bottom.svg
- src/app/(home)/cart/checkorder/page.tsx
- src/app/(home)/cart/confirm/page.tsx
> Feat: 장밥구니 최종 페이지 추가

- src/app/(home)/cart/now/_components/Accessory.tsx
- src/app/(home)/cart/now/_components/Hardware.tsx
- src/app/order/hardware/confirm/page.tsx
> Feat:  부속품 및 하드웨어 바로구매 코드 추가

- src/app/(home)/cart/now/_components/Accessory.tsx
- src/app/(home)/cart/now/_components/Finish.tsx
- src/app/(home)/cart/now/_components/Hardware.tsx
- src/app/order/finish/_components/ColorList.tsx
- src/app/order/finish/confirm/page.tsx
- src/app/order/finish/custom-color/page.tsx
- src/app/order/finish/page.tsx
- src/app/order/finish/select/_components/Depth.tsx
- src/app/order/finish/select/_components/Height.tsx
- src/app/order/finish/select/page.tsx
- src/app/order/hardware/confirm/page.tsx
> Feat: 마감재 페이지 추가

- src/app/(home)/cart/_components/Cabinet.tsx
- src/app/(home)/cart/now/_components/Cabinet.tsx
- src/app/(home)/cart/page.tsx
- src/app/order/cabinet/_components/CategorySection.tsx
- src/app/order/cabinet/color/custom-color/page.tsx
- src/app/order/cabinet/color/page.tsx
- src/app/order/cabinet/confirm/page.tsx
- src/app/order/cabinet/page.tsx
- src/app/order/cabinet/select/_components/Drawer.tsx
- src/app/order/cabinet/select/_components/Finish.tsx
- src/app/order/cabinet/select/_components/HandleType/Flap.tsx
- src/app/order/cabinet/select/_components/HandleType/Lower.tsx
- src/app/order/cabinet/select/_components/HandleType/Open.tsx
- src/app/order/cabinet/select/_components/HandleType/Upper.tsx
- src/app/order/cabinet/select/_components/Material.tsx
- src/app/order/cabinet/select/_components/Rail.tsx
- src/app/order/cabinet/select/_components/SizeInput.tsx
- src/app/order/cabinet/select/page.tsx
- src/constants/category.ts
- src/constants/modelList.ts
- src/store/Items/cabinetStore.ts
> Feat: 부분장 추가

- src/app/login/page.tsx
- src/app/order/accessory/select/page.tsx
- src/app/order/cabinet/select/page.tsx
- src/app/order/door/select/page.tsx
- src/app/order/finish/select/page.tsx
- src/app/order/hardware/select/page.tsx
- src/types/apiType.d.ts
> Refactor: api 페이지별 연결

- src/app/(home)/_components/CategorySection.tsx
- src/app/(home)/cart/_components/Accessory.tsx
- src/app/(home)/cart/_components/Cabinet.tsx
- src/app/(home)/cart/_components/CartItemDetail.tsx
- src/app/(home)/cart/_components/Door.tsx
- src/app/(home)/cart/_components/Finish.tsx
- src/app/(home)/cart/_components/Hardware.tsx
- src/app/(home)/cart/checkorder/page.tsx
- src/app/(home)/cart/page.tsx
- src/app/order/door/confirm/page.tsx
- src/app/order/door/select/_components/Normal.tsx
- src/app/order/door/select/page.tsx
- src/components/Input/Input.tsx
> Fix: error

- src/app/(home)/cart/_components/Accessory.tsx
- src/app/(home)/cart/_components/Cabinet.tsx
- src/app/(home)/cart/_components/Door.tsx
- src/app/(home)/cart/_components/Finish.tsx
- src/app/(home)/cart/_components/Hardware.tsx
- src/app/(home)/cart/confirm/page.tsx
> Fix: 페이지 추가 수정

- back/.gitattributes
- back/.gitignore
- back/dist/authHandler.js
- back/dist/index.js
- back/dist/orderHandler.js
- back/dist/prismaClient.js
- back/package-lock.json
- back/package.json
- back/prisma/schema.prisma
- back/src/authHandler.ts
- back/src/index.ts
- back/src/orderHandler.ts
- back/src/prismaClient.ts
- back/tsconfig.json
- tsconfig.json
> 시험 이전까지 완성했던 backend 작업 내용(authentication 관리) merge 테스트입니다
> backend file added

- back/package-lock.json
- back/package.json
- back/prisma/migrations/20250715123415_enum_migration/migration.sql
- back/prisma/schema.prisma
- back/src/controllers/cartItemController.ts
- back/src/controllers/orderController.ts
- back/src/index.ts
- back/src/services/notionService.ts
> notion notify added

- src/api/authApi.ts
- src/api/cartItemApi.ts
- src/app/(home)/order/accessory/confirm/page.tsx
- src/app/(home)/order/cabinet/confirm/page.tsx
- src/app/(home)/order/door/confirm/page.tsx
- src/app/(home)/order/door/page.tsx
- src/app/(home)/order/finish/confirm/page.tsx
- src/app/login/page.tsx
- src/app/login/step/page.tsx
> feat:localApiTest

- back/prisma/migrations/20250717025133_change_user_type_to_enum/migration.sql
- back/prisma/migrations/20250717030044_/migration.sql
- back/prisma/schema.prisma
- back/src/controllers/authController.ts
- back/src/controllers/cartItemController.ts
- back/src/controllers/orderController.ts
- back/src/services/notionService.ts
unit_price added
authentication user_id response added
> ERD updated

- back/src/controllers/appUserController.ts
get api에서 도로명/상세 주소 역시 가져오도록 수정 완료
> user get api edited

- back/dist/index.js
> added netlify cors origin

- back/src/routes/auth.ts
> signup routing edited

- back/prisma/migrations/20250723103004_orderitem/migration.sql
- back/prisma/schema.prisma
- back/src/controllers/orderItemController.ts
- back/src/index.ts
- back/src/routes/order_item.ts
order_item ERD 반영 schema 수정
라우팅 및 컨트롤러 api 명세에 맞게 구현 완료
> order item implemented

- src/app/(home)/order/accessory/confirm/page.tsx
- src/app/(home)/order/accessory/page.tsx
- src/app/(home)/order/cabinet/page.tsx
- src/app/(home)/order/finish/page.tsx
- src/app/(home)/order/hardware/confirm/page.tsx
- src/app/(home)/order/hardware/page.tsx
- src/store/singleCartStore.ts
> refactor:formtest

- src/app/(home)/cart/CartClient.tsx
- src/app/(home)/cart/confirm/_components/OrderConfirmCard.tsx
- src/app/(home)/cart/confirm/page.tsx
- src/types/newItemTypes.d.ts
- src/utils/getCategoryLabel.ts
- cart페이지에서 보이는 상품카드 속성들 수정
- cart/confirm페이지 전용 카드 컴포넌트 생성 -> 기존 ShoppingCartCard와 구조는 유사하지만, 추후 confirm 페이지에서 디자인이 달라질 가능성을 고려해 별도의 컴포넌트로 분리
> Refactor: cart 페이지 상품 카드 속성 정리, confirm 페이지 전용 카드 컴포넌트 생성 적용

- back/src/controllers/cartController.ts
> fix: cart get method

- src/app/(home)/order/cabinet/_components/DrawerCabinetForm.tsx
- src/app/(home)/order/cabinet/_components/FlapCabinetForm.tsx
- src/app/(home)/order/cabinet/_components/LowerCabinetForm.tsx
- src/app/(home)/order/cabinet/_components/OpenCabinetForm.tsx
- src/app/(home)/order/cabinet/_components/UpperCabinetForm.tsx
- src/app/(home)/order/cabinet/hooks/useCabinetValidation.ts
- src/app/(home)/order/cabinet/page.tsx
- src/app/(home)/order/door/_components/DrawerDoorForm.tsx
- src/app/(home)/order/door/_components/FlapDoorForm.tsx
- src/app/(home)/order/door/_components/NormalDoorForm.tsx
- src/app/(home)/order/door/hooks/useDoorValidation.ts
- src/app/(home)/order/door/page.tsx
- src/app/(home)/order/finish/_components/DepthInputSection.tsx
- src/app/(home)/order/finish/_components/HeightInputSection.tsx
- src/app/(home)/order/finish/hooks/useFinishValidation.ts
- src/app/(home)/order/finish/page.tsx
- src/services/pricing/colorMapping.ts
- src/services/pricing/doorPricing.ts
- src/services/pricing/finishPricing.ts
> feat:validation logic added

- back/src/controllers/orderController.ts
- back/src/routes/order.ts
엔드포인트: order/orders?user_id={user_id}
기타 명세 사항은 노션에 추가되어 있습니다!
> order get api added
